namespace Sudoku.Solving.Asp;

/// <summary>
/// Indicates a solver that solves a sudoku puzzle by encoding the rules as Answer Set Programming (ASP) program,
/// and invoking <c>libclingo</c> (Potassco project) via P/Invoke.
/// </summary>
/// <remarks>
/// <para>
/// The sudoku rules are encoded as a constant ASP program (see <see cref="Program"/>);
/// given cells are appended as <c>puzzle(R, C, N)</c> facts generated by <see cref="GenerateFacts(in Grid)"/>.
/// The solution is reconstructed from the <c>cell(R, C, N)</c> atoms of the first model.
/// </para>
/// <para>
/// Requires <c>libclingo.so</c> (Linux), <c>libclingo.dylib</c> (macOS) or <c>clingo.dll</c> (Windows)
/// available in the runtime library search path.
/// </para>
/// </remarks>
public sealed class AspSolver : ISolver
{
	/// <summary>
	/// The ASP program encoding of the sudoku rules (9x9).
	/// </summary>
	private const string Program = """
		row(1..9).  col(1..9).  num(1..9).
		1 { cell(R, C, N) : num(N) } 1 :- row(R), col(C).
		:- row(R), num(N), #count { C : cell(R, C, N) } != 1.
		:- col(C), num(N), #count { R : cell(R, C, N) } != 1.
		subgrid(SG_R, SG_C, R, C) :- row(R), col(C), SG_R = (R-1)/3, SG_C = (C-1)/3.
		:- num(N), subgrid(SG_R, SG_C, _, _), #count { R, C : cell(R, C, N), subgrid(SG_R, SG_C, R, C) } != 1.
		:- puzzle(R, C, N), not cell(R, C, N).
		#show cell/3.
		""";


	/// <inheritdoc/>
	public string UriLink => "https://en.wikipedia.org/wiki/Answer_set_programming";


	/// <inheritdoc/>
	public bool? Solve(in Grid grid, out Grid result)
	{
		var control = (nint)0;
		var handle = (nint)0;
		var solutionCount = 0;
		var solution = Grid.Undefined;
		try
		{
			var args = new[] { "--models=0" };
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoControlNew(args, (nuint)args.Length, ClingoInterop.NoOpLoggerPtr, 0, 20, out control));
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoControlAdd(control, "base", [], 0, GenerateFacts(grid) + Program));

			var parts = new Part[] { new() { Name = "base", Parameters = 0, Size = 0 } };
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoControlGround(control, parts, (nuint)parts.Length, 0, 0));
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoControlSolve(control, ClingoInterop.SolveModeYield, 0, 0, 0, 0, out handle));

			// Enumerate at most 2 models to check the uniqueness of the solution.
			while (solutionCount < 2)
			{
				ClingoInterop.ThrowOnError(ClingoInterop.ClingoSolveHandleResume(handle));
				ClingoInterop.ThrowOnError(ClingoInterop.ClingoSolveHandleModel(handle, out var model));
				if (model == 0)
				{
					break;
				}

				solutionCount++;
				if (solutionCount == 1)
				{
					solution = ExtractSolution(model);
				}
			}
		}
		catch (ClingoException)
		{
			// Treat the puzzle as unsolved when libclingo is unavailable or an error occurs.
			result = Grid.Undefined;
			return null;
		}
		finally
		{
			if (handle != 0)
			{
				ClingoInterop.ClingoSolveHandleClose(handle);
			}

			if (control != 0)
			{
				ClingoInterop.ClingoControlFree(control);
			}
		}

		result = solution;
		return solutionCount switch { 0 => null, 1 => true, _ => false };
	}


	/// <summary>
	/// Converts the given digits of the grid into <c>puzzle(R, C, N)</c> facts (1-based coordinates).
	/// </summary>
	/// <param name="grid">The grid.</param>
	/// <returns>The fact string.</returns>
	private static string GenerateFacts(in Grid grid)
	{
		var sb = new StringBuilder();
		for (var cell = 0; cell < 81; cell++)
		{
			if (grid.GetDigit(cell) is var digit and not -1)
			{
				sb.Append("puzzle(").Append(cell / 9 + 1).Append(',').Append(cell % 9 + 1).Append(',').Append(digit + 1).AppendLine(").");
			}
		}

		return sb.ToString();
	}

	/// <summary>
	/// Reconstructs the full grid from the <c>cell/3</c> atoms of the model.
	/// </summary>
	/// <param name="model">The clingo model pointer.</param>
	/// <returns>The solution grid.</returns>
	private static Grid ExtractSolution(nint model)
	{
		ClingoInterop.ThrowOnError(ClingoInterop.ClingoModelSymbolsSize(model, ClingoInterop.ShowTypeShown, out var symbolCount));
		var symbols = new ulong[symbolCount];
		ClingoInterop.ThrowOnError(ClingoInterop.ClingoModelSymbols(model, ClingoInterop.ShowTypeShown, symbols, symbolCount));

		var buffer = new char[81];
		Array.Fill(buffer, '0');
		foreach (var symbol in symbols)
		{
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoSymbolName(symbol, out var namePtr));
			if (Marshal.PtrToStringAnsi(namePtr) != "cell")
			{
				continue;
			}

			ClingoInterop.ThrowOnError(ClingoInterop.ClingoSymbolArguments(symbol, out var argsPtr, out var argCount));
			if (argCount != 3)
			{
				continue;
			}

			// Reads the three argument symbols (8 bytes each) and extracts their values (1-based).
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoSymbolNumber((ulong)Marshal.ReadInt64(argsPtr, 0), out var row));
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoSymbolNumber((ulong)Marshal.ReadInt64(argsPtr, 8), out var column));
			ClingoInterop.ThrowOnError(ClingoInterop.ClingoSymbolNumber((ulong)Marshal.ReadInt64(argsPtr, 16), out var digit));
			buffer[(row - 1) * 9 + (column - 1)] = (char)('0' + digit);
		}

		return Grid.Parse(buffer);
	}
}
